server:
  port: 8090

spring:
  mongodb:
    embedded:
      version: 4.0.0
  main:
    allow-bean-definition-overriding: true


cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      access-key: localstack
      secret-key: localstack
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/372431383879

aws:
  queue:
    name: notificacao-pagamento-sync

mongodb:
  authentication-database: admin
  database: fast-food-pagamento
  url: mongodb://fast_food_pagamento_admin:fast_food_pagamento_root@fast-food-docdb-cluster.cluster-csxw4cuf3uvj.us-east-1.docdb.amazonaws.com:27017/?tls=true&tlsCAFile=global-bundle.pem&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
  username: fast_food_pagamento_admin
  password: fast_food_pagamento_root