server:
  port: 8090

spring:
  mongodb:
    embedded:
      version: 4.0.0
  main:
    allow-bean-definition-overriding: true


cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    credentials:
      access-key: localstack
      secret-key: localstack
    end-point:
      uri: http://localhost:4566

aws:
  queue:
    name: notificacao-pagamento-sync

#aws:
#  sqs:
#    notificacao-pagamento-sync:
#      url: http://localhost:4566/000000000000/notificacao-pagamento-sync.fifo

mongodb:
  authentication-database: admin
  database: fast-food-pagamento
  url: mongodb://127.0.0.1:27017
  username: root
  password: rootpassword