version: '3'
services:
  localstack:
    image: localstack/localstack:0.11.5
    ports:
      - "4566-4584:4566-4584"
      - "8080:8080"
    environment:
      - SERVICES=${SERVICES- ssm}
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
